global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]


  - job_name: "dogs"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ["172.22.112.1:8082"]

  - job_name: "volunteers"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "172.22.112.1:8083" ]

  - job_name: "users"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "172.22.112.1:8084" ]

  - job_name: "adoptions"
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "172.22.112.1:8085" ]