filebeat.inputs:
  - type: filestream
    id: app-logs
    enabled: true
    paths:
      - '/var/log/app_logs/dogs/*.log'
      - '/var/log/app_logs/volunteers/*.log'
      - '/var/log/app_logs/users/*.log'
      - '/var/log/app_logs/adoptions/*.log'

output.logstash:
  hosts: ['${LOGSTASH_HOST:localhost:5085}']